<?php
$title = 'View Result';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('game', array('action' => 'viewresult')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();