<?php

$title = 'Create game';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('game', array('action' => 'creategame')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('player1Name'));
echo $this->formRow($form->get('player1Email'));
echo $this->formRow($form->get('player2Name'));
echo $this->formRow($form->get('player2Email'));
echo $this->formRow($form->get('player1Choice'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();