<?php

$title = 'The Game';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('game', array('action'=>'creategame'));?>">Create new game</a>
    
    <?php 
    
	    for($pos = 0; $pos<count($highscore); $pos++) {
	    	$temp = array_slice($highscore, $pos, 1, true);
			echo "<p>".key($temp)." | ".$highscore[key($temp)]."</p>";
	    }
    ?>
</p>
