<?php
$title = 'Join game';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
if($error != ""){
	echo $error;
}

$form = $this->form;
$form->setAttribute('action', $this->url('game', array('action' => 'joingame')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('player2Choice'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();