
<?php

$title = 'Spiel erstellen!';
$this->headTitle($title);
?>


<h1><?php echo $this->escapeHtml($title); ?></h1>

<script type="text/javascript">
	var readyStateCheckInterval = setInterval(function() {
	    if (document.readyState === "complete") {
	        setUpCreateGame();
	        clearInterval(readyStateCheckInterval);
	    }
	}, 100);
</script>

<form name="createGame"  method="post">
	<div class="widget-content">
    	<div class="widget-box">
        	<div class = 'form-horizontal well'>

				<div class="control-group ">
                	<label class="control-label" for="player1Name">Geben Sie Ihren Namen ein: </label>
                    <div class="controls">
						<input type="text" name="player1Name" id="player1Name" value="<?php if($replaygame != null){echo $replaygame->player2Name;}?>" />
						<div id="player1NameError"></div>
					</div>
				</div>
				
				<div class="control-group">
                	<label class="control-label" for="player1Email">Geben Sie Ihre E-Mail ein: </label>
                    <div class="controls">
						<input type="text" name="player1Email" id="player1Email" value="<?php if($replaygame){echo $replaygame->player2Email;}?>" />
						<div id="player1EmailError"></div>
					</div>
				</div>
				
				<div class="control-group">
                	<label class="control-label" for="player2Name">Geben Sie den Namen des Gegners ein: </label>
                    <div class="controls">
						<input type="text" name="player2Name" id="player2Name" value="<?php if($replaygame){echo $replaygame->player1Name;}?>" />
						<div id="player2NameError"></div>
					</div>
				</div>
				
				<div class="control-group">
                	<label class="control-label" for="player2Email">Geben Sie die E-Mail des Gegners ein: </label>
                    <div class="controls">
						<input type="text" name="player2Email" id="player2Email" value="<?php if($replaygame){echo $replaygame->player1Email;}?>" />
						<div id="player2EmailError"></div>
					</div>
				</div>
				
				<div class="control-group">
                	<label class="control-label">W&auml;hlen Sie Ihre Waffe: </label>
                    <div class="controls">
						<input type="hidden" name="player1Choice" id="player1Choice" value="0" />
						<div id="player1ChoiceError"></div>
						
						<a href="#" onclick="setNewWeapon('player1Choice', '1');return false;" >
							<img id="rockImg" src="<?php echo $this->basePath("img/Rock.jpg"); ?>" alt="Rock" title="Stein" height="150" width="150"/>
						</a>
						<a href="#" onclick="setNewWeapon('player1Choice', '2');return false;" >
							<img id="scissorsImg" src="<?php echo $this->basePath("img/Scissors.jpg"); ?>" alt="Scissors" title="Schere" height="150" width="150"/>
						</a>
						<a href="#" onclick="setNewWeapon('player1Choice', '3');return false;" >
							<img id="paperImg" src="<?php echo $this->basePath("img/Paper.jpg"); ?>" alt="Paper" title="Papier" height="150" width="150"/>
						</a>
						<a href="#" onclick="setNewWeapon('player1Choice', '4');return false;" >
							<img id="lizardImg" src="<?php echo $this->basePath("img/Lizard.jpg"); ?>" alt="Lizard" title="Echse" height="150" width="150"/>
						</a>	
						<a href="#" onclick="setNewWeapon('player1Choice', '5');return false;" >
							<img id="spockImg" src="<?php echo $this->basePath("img/Spock.jpg"); ?>" alt="Spock" title="Spock" height="150" width="150"/>
						</a>
					</div>
				</div>
				
				<div class="control-group">
                	<label class="control-label" for="player1Message">Sie k&ouml;nnen eine Nachricht f&uuml;r Ihren Gegner hinterlassen: </label>
                    <div class="controls">
						<textarea name="player1Message" id="player1Message" value=""></textarea>
					</div>
				</div>
				
				<div class="control-group">
                    <div class="controls">
						<button class="btn-primary" onClick="return checkCreateForm('<?php echo $this->url('game', array('action' => 'creategame'))?>');">Spiel erstellen</button>
					</div>
				</div>
				
			</div>
		</div>
	</div>
</form>