<?php

$title = 'Stein Schere Papier Echse Spock';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<script type="text/javascript">
	$(document).ready(function() {
		window.history.pushState("object or string", "Title", "/aufgabe9/game");
	});
</script>



<div class="row-fluid">

<div class="span7">
	<img src="<?php echo $this->basePath("img/gameRules.jpg"); ?>"/>
	<br><br>
	<p>
	Die Regeln von Stein-Schere-Papier-Echse-Spock sind:<br>
	</p>
	<ul>	
		<li>Schere schneidet Papier</li>
		<li>Papier bedeckt Stein</li>
		<li>Stein zerquetscht Echse</li>
		<li>Echse vergiftet Spock</li>
		<li>Spock zertr&uuml;mmert Schere</li>
		<li>Schere k&ouml;pft Echse</li>
		<li>Echse frisst Papier</li>
		<li>Papier widerlegt Spock</li>
		<li>Spock verdampft Stein</li>
		<li>Stein schleift Schere</li>
	</ul>
	
</div>

<div class="span5">
	<h3>Highscore</h3>
	
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Siege</th>
			</tr>
		</thead>
		<tbody id="tableBody">
			<?php				
				for($pos = 0; $pos<count($highscore); $pos++) {
					$temp = array_slice($highscore, $pos, 1, true);
					echo "<tr><td>".key($temp)."</td><td>".$highscore[key($temp)]."<td></tr>";
				}
			?>
		</tbody>
	</table> 
	<script>getHighscoreList('<?php echo $this->url('game', array('action' => 'index'))?>')</script>
</div>

</div>


