<?php

$title = 'Stein Schere Papier Echse Spock';
$this->headTitle($title);
?>

<script type ="text/javascript">
$(document).ready(function(){
	setUpCreateGame();
	setUpJoinGame();
});

</script>

<div id="index">
	<h1><?php echo $this->escapeHtml($title); ?></h1>
	
	<div class="row-fluid">
	
	<div class="span7">
		<img src="<?php echo $this->basePath("img/gameRules.jpg"); ?>"/>
		<br><br>
		<p>
		Die Regeln von Stein-Schere-Papier-Echse-Spock sind:<br>
		</p>
		<ul>	
			<li>Schere schneidet Papier</li>
			<li>Papier bedeckt Stein</li>
			<li>Stein zerquetscht Echse</li>
			<li>Echse vergiftet Spock</li>
			<li>Spock zertr&uuml;mmert Schere</li>
			<li>Schere k&ouml;pft Echse</li>
			<li>Echse frisst Papier</li>
			<li>Papier widerlegt Spock</li>
			<li>Spock verdampft Stein</li>
			<li>Stein schleift Schere</li>
		</ul>
		
	</div>
	
	<div class="span5">
		<h3>Highscore</h3>
		
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Siege</th>
				</tr>
			</thead>
			<tbody id="tableBody">
				<?php				
					for($pos = 0; $pos<count($highscore); $pos++) {
						$temp = array_slice($highscore, $pos, 1, true);
						echo "<tr><td>".key($temp)."</td><td>".$highscore[key($temp)]."<td></tr>";
					}
				?>
			</tbody>
		</table> 
		<script>getHighscoreList('<?php echo $this->url('game', array('action' => 'index'))?>')</script>
	</div>
	
	</div>
</div>

<div id="create">
	<h1>Spiel erstellen</h1>
	
	<script type="text/javascript">
		var readyStateCheckInterval = setInterval(function() {
		    if (document.readyState === "complete") {
		        
		        clearInterval(readyStateCheckInterval);
		    }
		}, 100);
	</script>
	
	<form name="createGame"  method="post">
		<div class="widget-content">
	    	<div class="widget-box">
	        	<div class = 'form-horizontal well'>
	
					<div class="control-group ">
	                	<label class="control-label" for="player1Name">Geben Sie Ihren Namen ein: </label>
	                    <div class="controls">
							<input type="text" name="player1Name" id="player1Name" value="<?php if($replaygame != null){echo $replaygame->player2Name;}?>" />
							<div id="player1NameError"></div>
						</div>
					</div>
					
					<div class="control-group">
	                	<label class="control-label" for="player1Email">Geben Sie Ihre E-Mail ein: </label>
	                    <div class="controls">
							<input type="text" name="player1Email" id="player1Email" value="<?php if($replaygame){echo $replaygame->player2Email;}?>" />
							<div id="player1EmailError"></div>
						</div>
					</div>
					
					<div class="control-group">
	                	<label class="control-label" for="player2Name">Geben Sie den Namen des Gegners ein: </label>
	                    <div class="controls">
							<input type="text" name="player2Name" id="player2Name" value="<?php if($replaygame){echo $replaygame->player1Name;}?>" />
							<div id="player2NameError"></div>
						</div>
					</div>
					
					<div class="control-group">
	                	<label class="control-label" for="player2Email">Geben Sie die E-Mail des Gegners ein: </label>
	                    <div class="controls">
							<input type="text" name="player2Email" id="player2Email" value="<?php if($replaygame){echo $replaygame->player1Email;}?>" />
							<div id="player2EmailError"></div>
						</div>
					</div>
					
					<div class="control-group">
	                	<label class="control-label">W&auml;hlen Sie Ihre Waffe: </label>
	                    <div class="controls">
							<input type="hidden" name="player1Choice" id="player1Choice" value="0" />
							<div id="player1ChoiceError"></div>
							
							<a href="#" onclick="setNewWeapon('player1Choice', '1');return false;" >
								<img id="rockImg" src="<?php echo $this->basePath("img/Rock.jpg"); ?>" alt="Stein" title="Stein" height="150" width="150"/>
							</a>
							<a href="#" onclick="setNewWeapon('player1Choice', '2');return false;" >
								<img id="scissorsImg" src="<?php echo $this->basePath("img/Scissors.jpg"); ?>" alt="Schere" title="Schere" height="150" width="150"/>
							</a>
							<a href="#" onclick="setNewWeapon('player1Choice', '3');return false;" >
								<img id="paperImg" src="<?php echo $this->basePath("img/Paper.jpg"); ?>" alt="Papier" title="Papier" height="150" width="150"/>
							</a>
							<a href="#" onclick="setNewWeapon('player1Choice', '4');return false;" >
								<img id="lizardImg" src="<?php echo $this->basePath("img/Lizard.jpg"); ?>" alt="Echse" title="Echse" height="150" width="150"/>
							</a>	
							<a href="#" onclick="setNewWeapon('player1Choice', '5');return false;" >
								<img id="spockImg" src="<?php echo $this->basePath("img/Spock.jpg"); ?>" alt="Spock" title="Spock" height="150" width="150"/>
							</a>
							<div id="weaponDescription"></div>
						</div>
					</div>
					
					<div class="control-group">
	                	<label class="control-label" for="player1Message">Sie k&ouml;nnen eine Nachricht f&uuml;r Ihren Gegner hinterlassen: </label>
	                    <div class="controls">
							<textarea name="player1Message" id="player1Message" value=""></textarea>
						</div>
					</div>
					
					<div class="control-group">
	                    <div class="controls">
							<button class="btn-primary" onClick="return checkCreateForm('<?php echo $this->url('game', array('action' => 'creategame'))?>');">Spiel erstellen</button>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</form>

</div>

<div id="createdGame">
	<h1>Spiel wurde erstellt</h1>
	
	<p id="confirm"></p>

</div>


<div id="joinGame">
	<form name="joinGame"  method="post">
		<div class="widget-content">
	    	<div class="widget-box">
	        	<div class = 'form-horizontal well'>
					<div class='control-group'>
						<label class='control-label'>Dein Gegner hat dir eine Nachricht hinterlassen</label>
						<div class='controls'>
							<p id="message"></p>
						</div>
					</div>

					<div class="control-group">
	                	<label class="control-label">Ihre Name: </label>
	                    <div class="controls">
	                    	<input type="text" name="player2Name" id="joinPlayer2Name" value=""/>
	                    	<div id="joinPlayer2NameError"></div>
						</div>
					</div>
	        		        	
					<div class="control-group">
	                	<label class="control-label">W&auml;hle deine Waffe: </label>
	                    <div class="controls">
	                    	<input type="hidden" name="id" id="joinId" value=""/>
							<input type="hidden" name="player2Choice" id="player2Choice" value="0" />
							<div id="player2ChoiceError"></div>
					
							<a href="#" onclick="setNewWeapon('player2Choice', '1')" >
								<img id="rockImgJoin" src="<?php echo $this->basePath("img/Rock.jpg"); ?>" alt="Rock" title="Stein" height="150" width="150"/>
							</a>
							<a href="#" onclick="setNewWeapon('player2Choice', '2')" >
								<img id="scissorsImgJoin" src="<?php echo $this->basePath("img/Scissors.jpg"); ?>" alt="Scissors" title="Schere" height="150" width="150"/>
							</a>
							<a href="#" onclick="setNewWeapon('player2Choice', '3')" >
								<img id="paperImgJoin" src="<?php echo $this->basePath("img/Paper.jpg"); ?>" alt="Paper" title="Papier" height="150" width="150"/>
							</a>
							<a href="#" onclick="setNewWeapon('player2Choice', '4')" >
								<img id="lizardImgJoin" src="<?php echo $this->basePath("img/Lizard.jpg"); ?>" alt="Lizard" title="Echse" height="150" width="150"/>
							</a>	
							<a href="#" onclick="setNewWeapon('player2Choice', '5')" >
								<img id="spockImgJoin" src="<?php echo $this->basePath("img/Spock.jpg"); ?>" alt="Spock" title="Spock" height="150" width="150"/>
							</a>
							<div id="joinWeaponDescription"></div>
						</div>
					</div>
					
					<div class="control-group">
	                	<label class="control-label" for="player2Message">Sie k&ouml;nnen eine Nachricht f&uuml;r Ihren Gegner hinterlassen: </label>
	                    <div class="controls">
							<textarea name="player2Message" id="player2Message" value=""></textarea>
						</div>
					</div>
					
					<div class="control-group">
	                    <div class="controls">
							<button onClick="return checkJoinForm('<?php echo $this->url('game', array('action' => 'joingame'))?>');" class="btn-primary">Spiel beitreten!</button>
						</div>
					</div>
					
				</div>
			</div>
		</div>
	</form>

</div>

<div id="result">
	<h1>Ergebnis</h1>
	
	<p id="resultError"></p>
	<p id="resultInfo"></p>

</div>


